chapter_twelve = {
    ("reminder",): ['die Mahnung'],
    ("sports club",): ['der Sportverein'],
    ("sum", "amount"): ['der Betrag', 'der Anteil', 'die Menge'],
    ("to govern",): ['regieren'],
    ("to buy", "to get"): ['anschaffen'],
    ("document",): ['der Beleg'],
    ("seriously",): ['ernsthaft'],
    ("economically",): ['sparsam'],
    ("coffee beans",): ['der Bohnenkaffee'],
    ("unity",): ['die Einheit'],
    ("men's suit",): ['der Herrenanzug'],
    ("wardrobe",): ['der Kleiderschrank'],
    ("brown bread",): ['das Mischbrot'],
    ("full milk",): ['die Vollmilch'],
    #in der bank
    ("to withdraw", "to lift off"): ['abheben'],
    ("debit card",): ['die EC-Karte'],
    ("ATM",): ['der Bankautomat', 'der Geldautomat'],
    ("checking account",): ['das Girokonto'],
    ("account opening",): ['die Kontoeröffnung'],
    ("dream bank",): ['die Traumbank'],
    ("free",): ['umsonst', 'kostenfrei', 'kostenlos'],
    ("fantastic", "fantastical"): ['traumhaft'],
    ("secret number",): ['die Geheimnummer', 'die Geheimzahl'],
    ("credit",): ['der Kredit'],
    ("PIN",): ['die PIN'],
    ("wallet",): ['das Portemonnaie'],
    ("native language",): ['die Umgangssprache'],
    ("bank customer",): ['der Bankkunde'],
    ("cash",): ['das Bargeld'],
    ("thankful", "thankfully"): ['dankbar'],
    ("to collect",): ['einziehen'],
    ("to increase",): ['erhöhen'],
    ("card",): ['die Karte'],
    ("account number",): ['die Kontonummer'],
    ("briefly",): ['kurzfristig'],
    ("to block",): ['sperren'],
    ("to overdraw",): ['überziehen'],
    ("to recharge",): ['aufladen'],
    ("to execute", "to carry out"): ['ausführen'],
    ("banking",): ['das Bankgeschäft'],
    ("meaning",): ['die Bedeutung'],
    ("to keep",): ['behalten'],
    ("to need", "to require"): ['benötigen'],
    ("to damage",): ['beschädigen'],
    ("recurring payment", "standing order"): ['der Dauerauftrag'],
    ("theft",): ['der Diebstahl'],
    ("to establish",): ['einrichten', 'errichten', 'gründen'],
    ("to take from",): ['entnehmen'],
    ("ticket machine",): ['der Fahrkartenautomat'],
    ("branch",): ['die Filiale'],
    ("sum of money",): ['der Geldbetrag'],
    ("to credit",): ['gutschreiben'],
    ("account withdrawal",): ['der Kontoauszug'],
    ("new customer",): ['der Neukunde'],
    ("parking meter",): ['der Parkautomat'],
    ("immediate(ly)",): ['umgehend'],
    ("loss",): ['der Verlust'],
    ("to manage",): ['verwalten', 'schaffen', 'bewältigen', 'leiten'],
    ("to find again",): ['wiederfinden'],
    ("to send over",): ['zuschicken'],
    ("to get back", "to receive back"): ['zurückerhalten'],
    ("to fill out",): ['ausfüllen'],
    ("to decline",): ['deklinieren'],
    ("to deposit", "to pay in"): ['einzahlen'],
    #total global
    ("globalization",): ['die Globalisierung'],
    ("Asia",): ['Asien'],
    ("selection", "choice"): ['die Auswahl', 'die Wahl', 'die Auslese'],
    ("banker",): ['der Banker'],
    ("to consider",): ['bedenken'],
    ("condition",): ['die Bedingung'],
    ("to be affected",): ['betroffen sein'],
    ("disturbing", "disturbingly"): ['beunruhigend', 'unruhig'],
    ("financial crisis",): ['die Finanzkrise'],
    ("research",): ['die Forschung'],
    ("progress",): ['der Fortschritt'],
    ("horrible",): ['furchtbar'],
    ("mobile phone manufacturer",): ['der Handyhersteller'],
    ("competition", "tournament"): ['die Konkurrenz', 'der Wettbewerb', 'das Turnier'],
    ("wage",): ['der Lohn'],
    ("problematic",): ['problematisch'],
    ("rapid",): ['rasend'],
    ("to speculate",): ['spekulieren'],
    ("top manager",): ['der Topmanager'],
    ("to survive",): ['überleben'],
    ("growing",): ['wachsend'],
    ("world market",): ['der Weltmarkt'],
    ("prosperity",): ['der Wohlstand'],
    ("to sweat",): ['schwitzen'],
    ("promise",): ['das Versprechen'],

    ("conscience",): ['das Gewissen'],
    ("based on",): ['basieren auf'],
    ("to betray", "to cheat"): ['betrügen', 'verraten', 'preisgeben', 'hintergehen', 'verrat begehen', 'die Treue brechen', 'im Stich lassen'],
    ("thief",): ['der Dieb'],
    ("in it",): ['drin'],
    ("to throw in", "to insert"): ['einwerfen'],
    ("question of conscience",): ['die Gewissensfrage'],
    ("great aunt",): ['die Großtante'],
    ("to find out",): ['herausfinden'],
    ("to review",): ['nachprüfen'],
    ("dusty",): ['verstaubt'],
    ("accusation",): ['der Vorwurf'],
    ("to re-gift",): ['weiterverschenken'],
    ("beautiful",): ['wunderschön'],
    ("newspaper rack",): ['der Zeitungskasten'],
    ("meanwhile", "in the meantime"): ['zwischendurch', 'mittlerweile', 'inzwischen', 'währenddessen', 'indes'],
    ("to advocate",): ['befürworten'],
    ("eye contact",): ['der Blickkontakt'],
    ("to tolerate", "to stand"): ['leiden können'],
    ("to clear one's throat",): ['sich räuspern'],
    ("to tolerate",): ['tolerieren', 'dulden', 'erdulden', 'ertragen', 'vertragen', 'gewähren lassen'],

}
chapter_eleven = {
    ("waste", "garbage"): ["der abfall", "der müll"],
    ("exhaust",): ["das Abgas"],
    ("organization", "company"): ["der Betrieb", "die Firma", "das Unternehmen", "die organization"],
    ("dirt", "dust", "stain"): ["der dreck", "der Staub", "der Fleck", "der Schmutz"],
    ("roadway",): ["die Fahrbahn"],
    ("automobile",): ["das Fahrzeug"],
    ("pedestrian zone",): ["die Fußgängerzone"],
    ("area", "territory", "region"): ["das Gebiet", "die Gegend", "der Landstrich", "die Region"],
    ("sidewalk",): ["der Gehsteig"],
    ("speed", "velocity"): ["die Geschwindigkeit", "das Tempo"],

    ("noise",): ["der Lärm", "das Geräusch", "die Störung"],
    ("edge", "outskirts"): ["der Rand"],
    ("display window",): ["das Schaufenster"],
    ("part of town", "quarter"): ["der Stadtteil"],
    ("city center",): ["das Stadtzentrum"],
    ("quarter",): ["das Viertel"],
    ("zone",): ["die Zone"],
    ("shopping street",): ["die Einkaufsstraße"],
    ("to concern",): ["angehen"],
    ("workweek",): ["die Arbeitswoche"],

    ("constantly", "continuous"): ["dauernd"],
    ("interculturally", "intercultural"): ["interkulturell"],
    ("no more", "never again"): ["nie mehr","nicht mehr"],
    ("to agree",): ["sich einigen", "zustimmen", "recht geben"],
    ("shopping",): ["das Shopping","der Einkauf"],
    ("city person",): ["der Stadtmensch", "der Stadttyp"],
    ("student life",): ["das Studentenleben"],
    ("country person",): ["der Landmensch"],
    ("city garden",): ["der Stadtgarten"],
    ("to awaken", "to wake up"): ["erwachen", "aufwachen"],

    ("bakery",): ["die Backstube"],
    ("construction yard",): ["der Bauhof"],
    ("work", "service"): ["der Dienst","die dienstleistung","der service"],
    ("to be in service",): ["im Dienst sein"],
    ("morning shift",): ["die Frühschicht"],
    ("to go in",): ["hineingehen", "reingehen"],
    ("full speed",): ["die Hochtouren"],
    ("basket",): ["der Korb"],
    ("trainee",): ["der Lehrling"],
    ("magazine report",): ["der Magazinbericht"],

    ("operation", "surgery"): ["die Operation"],
    ("street cleaning vehicle",): ["das Reinigungsfahrzeug"],
    ("urban",): ["städtisch"],
    ("adoption","takeover"): ["die Übernahme"],
    ("unsettled", "uneasy", "uneasily"): ["unruhig", "beunruhigend"],
    ("way", "path"): ["der Weg","die Strecke"],
    ("driver",): ["der Fahrer"],
    ("night shift",): ["der Nachtdienst"],
    ("to leave open",): ["offen lassen"],
    ("usual", "common"): ["üblich"],

    ("social worker",): ["der Sozialarbeiter"],
    ("to happen", "to occur"): ["geschehen", "vorkommen", "passieren", "stattfinden"],
    ("worth living",): ["lebenswert"],
    ("to attract", "to pull in"): ["anziehen"],
    ("job searcher",): ["der Arbeitssuchende"],
    ("trainee position",): ["der Ausbildungsplatz"],
    ("to evaluate", "to assess"): ["bewerten"],
    ("to serve as",): ["dienen als"],
    ("income distribution",): ["die Einkommensstruktur"],
    ("information source",): ["die Informationsquelle"],

    ("investor",): ["der Investor"],
    ("criterion",): ["das Kriterium"],
    ("list",): ["die Liste"],
    ("ministry",): ["das Ministerium"],
    ("rank",): ["der Rang"],
    ("ranking",): ["das Ranking", "der Rankingplatz"],
    ("other",): ["sonstige"],
    ("front",): ["vordere"],
    ("city ranking",): ["das Städteranking"],
    ("recreational opportunity",): ["die Freizeitmöglichkeit"],

    ("salary level",): ["das Gehaltsniveau"],
    ("topic","theme"): ["der Themenbereich"],
    ("subtopic",): ["das Unterthema"],
    ("satisfaction",): ["die Zufriedenheit"],
    ("course location",): ["der Kursort"],
    ("to be in agreement",): ["sich einig sein"],
    ("continuous",): ["kontinuierlich", "fortlaufend"],
    ("interested person",): ["der Interessierte", "die Interessierte"],
    ("to stop",): ["anhalten", "stoppen", "aufhalten"],
    ("homeless person",): ["der Obdachlose", "die Obdachlose", "die obdachlose Person"],

    # ("change of shifts",): ["der Schichtwechsel","der Dienstwechsel"],
    # ("context",): ["der Zusammenhang","der Kontext"],
    # ("indeed",): ["allerdings", "zwar", "tatsächlich","in der Tat"],
    # ("colognian",): ["Kölsch"],
    # ("opening hours",): ["die Öffnungszeiten"],
    # ("holiday",): ["der Feiertag","der Urlaub"],
    # ("idea",): ["die Ahnung","die Idee"],
    # ("to smile at",): ["anlächeln"],
    # ("attraction",): ["die Attraktion"],
    # ("booth", "kiosk"): ["das Büdchen", "die Bude","der Kiosk"],

    # ("chips",): ["die Chips"],
    # ("curry",): ["das Currygewürz"],
    # ("dialect",): ["der Dialekt","die Mundart"],
    # ("floor", "story", "level"): ["die Etage", "das Stockwerk", "der Stock"],
    # ("to arrest",): ["festnehmen","verhaften"],
    # ("escape",): ["die Flucht","das Entkommen"],
    # ("to race down",): ["hinunterrasen"],
    # ("chicken meat",): ["das Hühnerfleisch"],
    # ("to rumble",): ["knurren"],
    # ("crime story", "crime film"): ["der Krimi"],

    # ("shop",): ["der Laden"],
    # ("long ago",): ["längst","vor langer Zeit"],
    # ("stomach",): ["der Magen","der Bauch"],
    # ("sandwich",): ["der Sandwich"],
    # ("city guide",): ["der Stadtführer"],
    # ("local pub",): ["die Stammkneipe"],
    # ("offender", "culprit"): ["der Täter"],
    # ("dead person",): ["der Tote"],
    # ("to be over",): ["um sein","vorbei sein","zu Ende sein" ],
    # ("suspect",): ["der Verdächtige"],

    # ("sales booth",): ["der Verkaufsstand"],
    # ("to question", "to examine"): ["vernehmen","untersuchen", "überprüfen","nachprüfen"],
    # ("witness",): ["der Zeuge"],
    # ("free activity",): ["die Freizeitaktivität"],
    # ("tourism",): ["der Tourismus"],
    # ("friendly",): ["freundlich"],
    # ("honored",): ["geehrt"],
    # ("business partner",): ["der Geschäftspartner"],
    # ("to notify", "to tell"): ["mitteilen"],
    # ("column",): ["die Spalte"]
}
chapter_ten = {
    ("honesty", "sincerity", "truthfulness"): ['die Ehrlichkeit'],
    ("fairness", "equity", "justice"): ['die Fairness', 'die Gerechtigkeit'],
    ("equality", "equal rights", "parity"): ['die Gleichberechtigung', 'die Chancengleichheit', 'die Gleichwertigkeit'],
    ("helpfulness", "willingness to help", "cooperativeness", "support"): ['die Hilfsbereitschaft', 'die Unterstützung'],
    ("respect",): ['der Respekt'],
    ("tolerance",): ['die Toleranz'],
    ("open-mindedness",): ['die Offenheit'],
    ("acceptance",): ['die Akzeptanz'],
    ("value", "principle"): ['der Wert', 'das Prinzip'],

    ("civic courage", "civil bravery", "moral courage", "civic duty"): ['die Zivilcourage', 'der Bürgermut'],
    ("allocation",): ['die Zuordnung', 'die Aufteilung', 'die Zuweisung'],
    ("to take a vote", "to vote"): ['abstimmen', 'wählen'],

    ("deputy", "representative"): ['der Abgeordnete', 'der Vertreter'],
    ("present",): ['anwesend'],
    ("to be around",): ['zugegen sein'],

    ("recording",): ['die Aufnahme'],
    ("to inspire", "to excite"): ['begeistern', 'inspirieren', 'anregen'],

    ("disabled", "impaired"): ['behindert', 'beeinträchtigt'],
    ("blind person",): ['der Blinde'],
    ("chancellor",): ['der Bundeskanzler', 'die Bundeskanzlerin'],

    ("German legislature", "federal parliament"): ['der Bundestag'],
    ("mayor", "municipal leader"): ['der Bürgermeister', 'das Stadtoberhaupt'],
    ("naturalization", "citizenship process"): ['die Einbürgerung', 'die Staatsbürgerschaftsverleihung'],

    ("immigrant", "incomer", "newcomer"): ['der Einwanderer', 'der Zuwanderer'],
    ("humorous", "funny", "witty"): ['humorvoll', 'witzig', 'amüsant'],

    ("candidate m/w",): ['die Kandidatin', 'der Kandidat'],
    ("physical", "bodily", "corporeal"): ['körperlich', 'physisch', 'leiblich'],

    ("minister", "secretary", "cabinet member"): ['der Minister', 'das Kabinettsmitglied'],
    ("political party", "party", "faction"): ['die Partei', 'die politische Gruppierung'],

    ("politics", "government affairs"): ['die Politik'],
    ("audience", "spectators", "viewers"): ['das Publikum', 'die Zuschauer', 'die Zuhörer'],
    ("right", "justice", "entitlement", "law"): ['das Recht', 'die Gerechtigkeit', 'die Berechtigung'],

    ("government", "administration", "regime"): ['die Regierung', 'die Verwaltung'],
    ("main focus", "center of gravity", "emphasis", "priority"): ['der Schwerpunkt', 'der Fokus', 'die Priorität'],
    ("to exercise", "to apply"): ['ausüben', 'praktizieren'],
    ("religion", "faith", "belief system"): ['die Religion', 'der Glaube'],
    ("to secure", "to ensure"): ['sichern', 'gewährleisten'],

    ("to alert", "to alarm"): ['alarmieren', 'warnen'],
    ("to notify",):['benachrichtigen'],
    ("job search", "job hunting", "employment search"): ['die Arbeitssuche', 'die Jobsuche', 'die Stellensuche'],
    ("to train", "to educate", "to instruct"): ['ausbilden', 'schulen', 'lehren', 'beibringen'],
    ("to move out",): ['ausrücken'],

    ("needy",): ['bedürftig', 'notleidend',"hilfsbedürftig","unterstützungsbedürftig"],
    ("visit to the authorities",): ['der Behördengang', 'der Amtsbesuch'],
    ("professional fire brigade",): ['die Berufsfeuerwehr'],

    ("to overcome", "to cope with", "to manage"): ["bewältigen", "überwinden", "überstehen"],
    ("to master",): ["beherrschen", "meistern"],
    ("roast",): ["der Braten"],
    ("to burn",): ["brennen"],
    ("voluntary", "unpaid", "charitable"): ["ehrenamtlich", "freiwillig"],

    ("complimentary",): ["unentgeltlich", "schmeichelhaft"],
    ("firefighters",): ["die Feuerwehrleute", "die Brandbekämpfer"],
    ("flood",): ["das Hochwasser", "die Überschwemmung", "die Flut"],
    ("meanwhile", "in the meantime"): ["inzwischen", "mittlerweile", "unterdessen","zwischendurch","indes","währenddessen"],
    ("training course", "seminar", "program"): ["der Lehrgang", "die Schulung", "das Seminar","das Program"],
    ("margarine",): ["die Margarine"],  # kind of butter
    ("mostly", "most of the time", "in most cases"): ["meist", "größtenteils", "hauptsächlich", "weitestgehend"],
    ("carrot",): ["die Möhre", "die Karotte", "die Mohrrübe"],
    ("nighttime", "night hours"): ["die Nachtzeit", "die nächtliche Zeit"],
    ("organization", "institution", "body", "union"): ["die Organisation", "die Einrichtung", "der Verband"],

    ("bandage",): ["der Verband"],
    ("godparent",): ["der Pate", "der Taufpate"],
    ("sponsorship",): ["die Patenschaft"],
    ("concern", "care", "nursing"): ["die Fürsorge", "die Betreuung", "die Pflege"],
    ("qualitative",): ["qualitativ"],
    ("difficulty", "challenge", "obstacle"): ["die Schwierigkeit", "das Problem", "die Hürde"],
    ("sauce", "gravy"): ["die Soße", "die Sauce"],
    ("to donate",): ["spenden", "geben", "stiften"],
    ("to contribute",): ["beitragen zu", "beisteuern zu"],
    ("association", "club", "society"): ["der Verein", "die Gemeinschaft", "die Vereinigung", "die Gesellschaft", "der Bund"],

    ("club member", "association member"): ["das Vereinsmitglied", "der Clubteilnehmer", "der Vereinsangehörige"],
    ("to destroy", "to annihilate"): ["vernichten", "zerstören", "auslöschen"],
    ("to extinguish",): ["löschen", "auslöschen"],
    ("to throw away", "to discard", "to dump"): ["wegwerfen", "entsorgen"],
    ("to eradicate",): ["beseitigen"],
    ("apartment search", "house hunting"): ["die Wohnungssuche"],
    ("nationwide",): ["bundesweit", "landesweit"],
    ("fire", "blaze"): ["der Brand", "das Feuer"],
    ("plot of land", "property", "site"): ["das Grundstück", "das Gelände", "das Areal"],
    ("deduction",): ["der Abzug", "die Kürzung"],
    ("to travel to", "to arrive"): ["anreisen", "ankommen", "eintreffen"],
    ("to pay off", "to be worth it"): ["sich auszahlen", "sich lohnen", "sich rechnen"],

    ("outside",): ["außerhalb + Genitiv"],
    ("already",): ["bereits", "schon"],
    ("to threaten",): ["drohen", "androhen", "bedrohen"],
    ("to register", "to note", "to enter", "to insert"): ["eintragen", "vermerken", "einfügen"],
    ("purchase", "buy", "shopping"): ["der Einkauf", "der Erwerb"],
    ("to open",): ["eröffnen"],
    ("global", "worldwide", "international"): ["global", "weltweit", "international"],
    ("hall", "auditorium"): ["die Halle", "der Saal"],
    ("university", "college", "institution of higher education"): ["die Hochschule", "die Universität", "die Fachhochschule"],
    ("within", "inside"): ["innerhalb + Genitiv"],
    ("career center", "job agency"): ["das Jobcenter", "die Arbeitsagentur"],

    ("youth group", "teen group"): ["die Jugendgruppe", "die Jugendgemeinschaft"],
    ("to play with",): ["mitspielen", "spielen mit", "teilnehmen am Spiel"],
    ("play money",): ["das Spielgeld"],
    ("play city",): ["die Spielstadt", "die Kinderspielstadt"],
    ("walkout",): ["die Arbeitsniederlegung"],
    ("place to study",): ["der Studienplatz", "der Studienort", "die Studienstätte"],
    ("time to study",): ["die Studienzeit", "die Studiumsdauer", "die Ausbildungszeit"],
    ("sale", "clearance"): ["der Verkauf", "der Ausverkauf", "der Sonderverkauf", "die Rabattaktion"],
    ("trained",): ["ausgebildet", "geschult", "qualifiziert", "geübt"],
    ("to keep clean",): ["sauber halten", "rein halten", "ordentlich halten"],
    ("to go on strike",): ["streiken", "in den Streik treten"],

    ("to put away",): ["wegräumen", "aufräumen"],

    ("to go there",): ["hingehen", "dorthin gehen"],
    ("north",): ["der Norden", "die Nordrichtung"],
    ("south",): ["der Süden", "die Südrichtung"],
    ("to clear away", "to eradicate"): ["abräumen", "wegräumen", "beseitigen"],

    ("shipment",): ["die Lieferung", "die Zustellung", "die Sendung", "die Warensendung"],
    ("streetlight",): ["die Straßenlaterne", "die Straßenlampe", "die Laterne"],
    ("uninteresting",): ["uninteressant", "langweilig", "öde"],
    ("Europe",): ["Europa"],
    ("EU", "European Union"): ["die EU", "die Europäische Union", "die Union"],
    ("European",): ["europäisch", "aus Europa"],
    ("union", "alliance"): ["die Union", "die Vereinigung", "der Zusammenschluss", "das Bündnis"],
    ("to decide on",): ["beschließen", "entscheiden"],
    ("the same",): ["dasselbe", "derselbe", "dieselbe", "identisch"],
    ("service",): ["die Dienstleistung", "der Service"],
    ("EU country",): ["das EU-Land", "das EU-Mitglied"],
    ("European Community",): ["die Europäische Gemeinschaft", "die EG"],

    ("border control",): ["die Grenzkontrolle"],
    ("national",): ["national", "staatlich"],
    ("lecture",): ["der Vortrag", "das Referat"],
    ("to preserve",): ["bewahren", "erhalten", "konservieren"],
    ("EU citizen",): ["der EU-Bürger", "der EU-Staatsbürger"],
    ("to build up", "to construct"): ["aufbauen", "errichten", "konstruieren", "gründen", "einrichten", "bauen"],
    ("structure",): ["die Struktur", "der Aufbau"],
    ("as follows",): ["folgendermaßen", "wie folgt", "nachstehend"],

}




